name: desaster
description: "A new Flutter project."
publish_to: "none"
version: 0.1.6

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^4.0.0
  flutter_map: ^7.0.0
  latlong2: ^0.9.1
  flutter_map_location_marker: ^9.0.0
  http: ^1.5.0
  location: ^8.0.1
  cloud_firestore: ^6.0.0
  toastification: ^3.0.3
  firebase_auth: ^6.0.2
  weather: ^3.2.1
  shared_preferences: ^2.2.2
  flutter_dotenv: ^5.1.0
  flutter_map_heatmap: 0.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  assets:
    - assets/logo.png
    - assets/initial_data.json
    - .env

  uses-material-design: true

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo.png"
  min_sdk_android: 21
