name: desaster
description: "A new Flutter project."
publish_to: "none"
version: 0.1.2

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^4.0.0
  flutter_map: ^8.2.1
  latlong2: ^0.9.1
  flutter_map_location_marker: ^10.1.0
  http: ^1.5.0
  location: ^8.0.1
  cloud_firestore: ^6.0.0
  toastification: ^3.0.3
  firebase_auth: ^6.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
