# Uncomment this line to define a global platform for your project
platform :ios, '15.0'

require 'json'

# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcworkspace', 'Contents.xcworkspacedata'), __FILE__)
  return unless File.exist?(generated_xcode_build_settings_path)
  require 'rexml/document'
  document = REXML::Document.new(File.new(generated_xcode_build_settings_path))
  root = document.root
  return root.elements['Workspace'].elements['FileRef'].attributes['location'].sub('group:', '').sub(/\A\/+/, '')
end

def flutter_ios_podfile_setup
  flutter_root_path = flutter_root
  return unless flutter_root_path
  symlink = flutter_root_path.start_with?('/') ? 'symlink' : 'copy'
  pod 'Flutter', :path => File.join(flutter_root_path, symlink, 'Flutter')
  pod 'FlutterPluginRegistrant', :path => File.join(flutter_root_path, symlink, 'FlutterPluginRegistrant')
end

def flutter_install_all_ios_pods(flutter_application_path = nil)
  flutter_application_path ||= File.expand_path('..', __dir__)
  flutter_root_path = flutter_root
  return unless flutter_root_path

  pod 'Flutter', :path => File.join(flutter_root_path, 'packages', 'flutter')

  plugin_pods_file = File.join(flutter_application_path, '.flutter-plugins-dependencies')
  if File.exist?(plugin_pods_file)
    plugin_pods = JSON.parse(File.read(plugin_pods_file))
    plugin_pods['plugins'].each do |plugin|
      pod plugin['name'], :path => File.join(flutter_application_path, 'ios', '.symlinks', 'plugins', plugin['name'], 'ios')
    end
  end
end

flutter_ios_podfile_setup

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.0'
      config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= ['$(inherited)']
      config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] << 'FIRCore_VERSION=12.0.0'
    end
  end
end
