name: Build iOS App

on:
  push:
    branches:
      - main  # Change to your default branch if different
    paths:
      - 'pubspec.yaml'

jobs:
  build-ios:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2  # Fetch last two commits to compare version

      - name: Check if version changed
        id: version-check
        run: |
          # Get current version from pubspec.yaml
          CURRENT_VERSION=$(grep '^version:' pubspec.yaml | sed 's/version: //')
          
          # Get previous version from the last commit
          git show HEAD~1:pubspec.yaml > pubspec_old.yaml 2>/dev/null || echo "version: 0.0.0" > pubspec_old.yaml
          PREVIOUS_VERSION=$(grep '^version:' pubspec_old.yaml | sed 's/version: //')
          
          echo "Current version: $CURRENT_VERSION"
          echo "Previous version: $PREVIOUS_VERSION"
          
          if [ "$CURRENT_VERSION" != "$PREVIOUS_VERSION" ]; then
            echo "Version changed, proceeding with build"
            echo "version_changed=true" >> $GITHUB_OUTPUT
          else
            echo "Version unchanged, skipping build"
            echo "version_changed=false" >> $GITHUB_OUTPUT
          fi

      - name: Setup Flutter
        if: steps.version-check.outputs.version_changed == 'true'
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.8.1'  # Match your pubspec.yaml SDK version

      - name: Install dependencies
        if: steps.version-check.outputs.version_changed == 'true'
        run: flutter pub get

      - name: Install CocoaPods dependencies
        if: steps.version-check.outputs.version_changed == 'true'
        run: |
          cd ios
          pod install

      - name: Build iOS release (no code sign)
        if: steps.version-check.outputs.version_changed == 'true'
        run: flutter build ios --release --no-codesign

      - name: Create unsigned archive
        if: steps.version-check.outputs.version_changed == 'true'
        run: |
          cd ios
          xcodebuild -workspace Runner.xcworkspace -scheme Runner -configuration Release -archivePath build/Runner.xcarchive archive CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO

      - name: Create pseudo-IPA from archive
        if: steps.version-check.outputs.version_changed == 'true'
        run: |
          cd ios/build
          mkdir -p Payload
          cp -r Runner.xcarchive/Products/Applications/Runner.app Payload/
          zip -r Runner.ipa Payload
          rm -rf Payload

      - name: Upload iOS build artifact
        if: steps.version-check.outputs.version_changed == 'true'
        uses: actions/upload-artifact@v4
        with:
          name: ios-build-${{ github.run_number }}
          path: ios/build/Runner.ipa
          retention-days: 30
